### ISSUE TITLE
Can't run because of Torchvision

### ISSUE THREAD

**Issue by mbeytekin** [Lornatang/DSGAN-PyTorch#1]
(base) PS E:\DSGAN-PyTorch-main> python test.py
Traceback (most recent call last):
  File "E:\DSGAN-PyTorch-main\test.py", line 22, in <module>
    import model
  File "E:\DSGAN-PyTorch-main\model.py", line 22, in <module>
    from torchvision.models.feature_extraction import create_feature_extractor
ModuleNotFoundError: No module named 'torchvision.models.feature_extraction'

I upgraded Torch and Torchvision but nothing changed. Do you have any idea?

**Comment by Lornatang** [comment]
torchvision version? 
torchvision==0.14.1?
